//Supabase config file

export const supabaseUrl = "https://rmghjtbtbsjusasmwivi.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZ2hqdGJ0YnNqdXNhc213aXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTkxMDY1NzYsImV4cCI6MjAxNDY4MjU3Nn0.CPPVXv1cHUen2OyPXiQxSCeLPD74HrSmt8hIzbxE3G8";
